### ISSUE TITLE
Error on home assistant startup

### ISSUE THREAD

**Issue by michaelmcneilnet** [mattrayner/pod-point-home-assistant-component#2]
## Version of the custom_component
0.2.0

## Card Configuration
```
type: entities
entities:
  - entity: sensor.pod_status
    name: Status
  - entity: binary_sensor.cable_status
    name: Cable
title: Pod Point
header:
  type: picture
  image: /api/pod_point/static/2c.png
  tap_action:
    action: none
  hold_action:
    action: none
state_color: true
show_header_toggle: true
```

## Logs

```txt
Logger: homeassistant.components.sensor
Source: custom_components/pod_point/sensor.py:50
Integration: Sensor (documentation, issues)
First occurred: 22:33:20 (2 occurrences)
Last logged: 22:33:20

Error adding entities for domain sensor with platform pod_point
Error while setting up pod_point platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 801, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 553, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 372, in state
    value = self.native_value
  File "/config/custom_components/pod_point/sensor.py", line 50, in native_value
    _LOGGER.info(self.extra_state_attributes[ATTR_STATE])
KeyError: 'state'
```

## Describe the bug
When I restart home assistant, I notice this error in the logs, and the status of the device and sensors are incorrect. After a few minutes the state of the sensors and device corrects itself, I assume on next reload of data from API?

**Comment by mattrayner** [comment]
This is because the integration in v2.0 did not automatically poll when you launched. This meant that for a while (5 minutes) there was an error accessing the data because nothing was there. As soon as the first poll happened the issue is fixed.

I've just release 3.0-beta4 which fixes this by polling immediately
