### ISSUE TITLE
Charging Allowed switch failing

### ISSUE THREAD

**Issue by mattcd216** [mattrayner/pod-point-home-assistant-component#48]
## Version of the custom_component
1.2.1
this also occurred after updating homeassistant core to 2024.2.0. I can see the .1 minor update available so will try that update next...

## Configuration

```
alias: Car charge off peak start
description: ""
trigger:
  - platform: state
    entity_id:
      - schedule.off_peak_electricity
    to: "on"
condition:
  - condition: state
    entity_id: device_tracker.car_device_tracker
    state: home
action:
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.podpoint_charging_allowed
mode: single
```

## Add your logs here.
```
Logger: homeassistant.components.automation.car_charge_off_peak_start
Source: components/automation/__init__.py:666
Integration: Automation (documentation, issues)
First occurred: 9 February 2024 at 00:00:00 (5 occurrences)
Last logged: 07:36:31

While executing automation automation.car_charge_off_peak_start
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 666, in async_trigger
    return await self.action_script.async_run(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1600, in async_run
    return await asyncio.shield(run.async_run())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 435, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 487, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 512, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 485, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 723, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 685, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/pod_point/switch.py", line 43, in async_turn_on
    await api.async_set_schedule(enabled=False, pod=self.pod)
  File "/usr/local/lib/python3.12/site-packages/podpointclient/client.py", line 123, in async_set_schedule
    await self.auth.async_update_access_token()
  File "/usr/local/lib/python3.12/site-packages/podpointclient/helpers/auth.py", line 63, in async_update_access_token
    access_token_updated: bool = await self.__update_access_token()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/podpointclient/helpers/auth.py", line 95, in __update_access_token
    response = await wrapper.post(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/podpointclient/helpers/api_wrapper.py", line 67, in post
    return await self.__wrapper(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/podpointclient/helpers/api_wrapper.py", line 183, in __wrapper
    raise exception
  File "/usr/local/lib/python3.12/site-packages/podpointclient/helpers/api_wrapper.py", line 128, in __wrapper
    response = await self._session.post(
                     ^^^^^^^^^^^^^^^^^^
AttributeError: 'Session' object has no attribute 'post'
```

## Describe the bug
I have an automation to enable charging during off-peak electricity (midnight to 5am). This has failed the last two nights in a row. Come the morning, if I 'reload' the integration the switch works (for a time).

**Comment by willenic** [comment]
I get the same behaviour.

`` "Session" object has no attribute "post" ``

If I delete and redownload it works initially but has failed the last two nights over night either leaving the car charging or not charging at at time I don't want it to.

![Screenshot_2024-02-10-08-16-38-31_c3a231c25ed346e59462e84656a70e50](https://github.com/mattrayner/pod-point-home-assistant-component/assets/144794340/84fb6a0b-b6ee-473f-8c83-b81b4d2ad1d9)

**Comment by mattrayner** [comment]
Hi everyone, thanks for reporting, it looks like there’s a bug related to
the 2024.2.x release of Home Assistant, the initial authorisation is
working then about an hour later it’s not able to re-authenticate.

I’ll take a deeper look this evening and try to pull together a fix :-)

**Comment by nickpearce95** [comment]
I am still on 2024.1.6 but experiencing the same behaviour - fixed temporarily by reloading the integration. 

Core 2024.1.6
Supervisor 2024.01.1
Operating System 11.4
Frontend 20240104.0

**Comment by mattrayner** [comment]
There was an authentication change made by Pod Point, this is likely related to that

**Comment by danielsmith89** [comment]
Bit of a dirty workaround, but I’ve added reloading the PodPoint integration to my automations, waiting for 30 seconds and then running the charging on/off switch. Seems to work, for now.

**Comment by mattrayner** [comment]
I believe I’ve found a fix, I’m testing it now but will hopefully have
something released tomorrow

**Comment by danielsmith89** [comment]
Awesome, thanks @mattrayner hopefully my workaround only needed tonight :)

**Comment by mattrayner** [comment]
@danielsmith89 @nickpearce95 @mattcd216 please try installing 1.2.2, I believe this fixes the issue :)

**Comment by willenic** [comment]
Seems to have sorted it, thanks Matt!
