### ISSUE TITLE
Static Path error after upgrade

### ISSUE THREAD

**Issue by garybrowngeo** [mattrayner/pod-point-home-assistant-component#63]
After upgarding to the latest integration I get the following error in the logs:

Logger: homeassistant.setup
Source: setup.py:251
First occurred: 09:19:07 (1 occurrences)
Last logged: 09:19:07

Setup failed for custom integration 'pod_point': Unable to import component: cannot import name 'StaticPathConfig' from 'homeassistant.components.http' (/usr/src/homeassistant/homeassistant/components/http/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/pod_point/__init__.py", line 14, in <module>
    from homeassistant.components.http import StaticPathConfig
ImportError: cannot import name 'StaticPathConfig' from 'homeassistant.components.http' (/usr/src/homeassistant/homeassistant/components/http/__init__.py)

**Comment by mattrayner** [comment]
Hi @garybrowngeo this is likely due to your Home Assistant version, what are you running?

I need to pin the latest version to a specific HA release I think

**Comment by garybrowngeo** [comment]
My versions are as follows:
Core
2024.2.5
Frontend
20240207.1

What do I need to do to fix?

**Comment by mattrayner** [comment]
I just pushed a new version of the integration that correctly 'pins' the required Home Assistant version, you currently have two options, roll back to `2.0.3` (and keep your existing Home Assistant version) or update to Home Assistant 2024.7 or greater to allow the new version to work correctly.

Note that all new versions of the integration will now require **at least** Home Assistant 2024.7
