### ISSUE TITLE
Blocking IO warning in HA

### ISSUE THREAD

**Issue by jamesonuk** [mattrayner/pod-point-home-assistant-component#71]
When starting HA there is a warning logged about blocking IO from this integration.

```
Logger: homeassistant.util.loop
Source: util/loop.py:77
First occurred: 24 December 2024 at 17:11:03 (1 occurrences)
Last logged: 24 December 2024 at 17:11:03

Detected blocking call to import_module with args ('custom_components.pod_point',) 
in /usr/src/homeassistant/homeassistant/loader.py, line 1074: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): 
 File "<frozen runpy>", line 198, in _run_module_as_main 
 File "<frozen runpy>", line 88, in _run_code 
 File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module> sys.exit(main()) 
 File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) 
 File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) 
 File "/usr/local/lib/python3.13/asyncio/base_events.py", line 708, in run_until_complete self.run_forever() 
 File "/usr/local/lib/python3.13/asyncio/base_events.py", line 679, in run_forever self._run_once() 
 File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2027, in _run_once handle._run() 
 File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) 
 File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) 
 File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component component = await integration.async_get_component() 
 File "/usr/src/homeassistant/homeassistant/loader.py", line 1026, in async_get_component comp = self._get_component() 
 File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path)
```

The issue looks to be the default used for the `aiohttp.ClientSession` in `__init__` in `client.py` in the underlying library
https://github.com/home-assistant/core/issues/121284

I will raise a PR against library

**Comment by jamesonuk** [comment]
@mattrayner this is largely cosmetic but https://github.com/mattrayner/podpointclient/pull/18 was merged to a 2.x branch but any change of a release of the client with this change in to remove an error in HA logs?
